# Firebolt Kafka Sink Connector version
version=0.4.4

# Gradle Configuration
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Project Information
group=com.firebolt
archivesBaseName=firebolt-kafka-connector
description=Kafka Connect Sink Connector for Firebolt Database