# when running from local desktop, then replace it with your specific clientId and clientSecret
clientId=AGrEqw9S3OI5wVlhxAf7oe1PoscgiPqQ
clientSecret=5VKeZNOVNDJTypjO0p5OPtMNGyQmMzIo4B-mcu7G3NrjG76AvD7NfJy_L-3ZOniu