name: All Core Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests (KC ${{ matrix.kafka_connect_version }}, Shard ${{ matrix.shard_index }})
    strategy:
      fail-fast: false
      matrix:
        kafka_connect_version: ['3.9.1', '4.0']
        shard_index: [0, 1, 2, 3, 4, 5]
    uses: ./.github/workflows/core-integration-tests.yml
    with:
      kafka_connect_version: ${{ matrix.kafka_connect_version }}
      shard_index: ${{ matrix.shard_index }}
      shard_total: 6
